#version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: innogram-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/db/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d innogram_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - innogram-network

  redis:
    image: redis:7-alpine
    container_name: innogram-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - innogram-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: innogram-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: innogram
      RABBITMQ_DEFAULT_PASS: innogram_password
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - innogram-network

  auth-microservice:
    build:
      context: ./apps/auth_microservice
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./apps/auth_microservice/auth.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - innogram-network

  core-microservice:
    build:
      context: ./apps/core_microservice
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./apps/core_microservice/core.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - innogram-network

  notifications-consumer-microservice:
    build:
      context: ./apps/notifications_consumer_microservice
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./apps/notifications_consumer_microservice/notifications-consumer.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - innogram-network

  nginx:
    image: nginx:1.27.4-bookworm
    ports:
      - "80:80"
    volumes:
      - ./apps/frontend/dist:/usr/share/nginx/html:ro
      - ./apps/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - innogram-network

volumes:
  postgres_data:
  redis_data:

networks:
  innogram-network:
    driver: bridge
