CREATE USER :DB_USER WITH PASSWORD :'DB_PASSWORD';

CREATE DATABASE :DB_NAME;

\c :DB_NAME

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS notification;

GRANT ALL PRIVILEGES ON DATABASE :DB_NAME TO :DB_USER;
GRANT ALL ON SCHEMA core TO :DB_USER;
GRANT ALL ON SCHEMA auth TO :DB_USER;
GRANT ALL ON SCHEMA notification TO :DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL ON TABLES TO :DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO :DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT ALL ON TABLES TO :DB_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT ALL ON SEQUENCES TO :DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO :DB_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT ALL ON SEQUENCES TO :DB_USER;

ALTER USER :DB_USER SET search_path TO core, auth, notification, public;

SELECT 'Database ' || :'DB_NAME' || ' created!' AS status;
SELECT 'User: ' || :'DB_USER' AS user_info;

