include:
  - path: ./docker-compose.infra.yaml
  - path: ./docker-compose.apps.yaml

# volumes:
#   postgres_data:
#   pgadmin_data:
#   redis_data:

# networks:
#   innogram-network:
#     driver: bridge
