"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/lib/query-provider";
import { Sidebar } from "@/components/layout/sidebar";
import { useMe } from "@/hooks/profile/use-me";
import { usePathname } from "next/navigation";
import { Toaster } from "sonner";
import { ModalProvider } from "@/components/provider/modal-provider";
import { NotificationsPanel } from "@/components/layout/notifications-panel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function AppLayout({ children }: { children: React.ReactNode }) {
  const { data: me, isLoading } = useMe();
  const pathname = usePathname();

  const isPublicPage = ["/login", "/signup"].includes(pathname);
  if (isLoading && !isPublicPage) {
    return (
      <div className="flex h-screen items-center justify-center">
        Loading...
      </div>
    );
  }

  return (
    <div className="flex min-h-screen">
      {/* Сайдбар отображается только если пользователь авторизован */}
      {me && <Sidebar />}

      {/* Контент страницы теперь будет занимать оставшееся место справа */}
      <main className="flex-1 bg-slate-50 dark:bg-black overflow-y-auto">
        {children}
      </main>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ModalProvider />
          <NotificationsPanel />
          <AppLayout>{children}</AppLayout>
          <Toaster position="top-right" richColors closeButton />
        </QueryProvider>
      </body>
    </html>
  );
}
