name: Test Core Microservice

on:
  pull_request:
    branches: [main, dev, "feature/INO-*"]
  push:
    branches: [main, dev, "feature/INO-*"]
  workflow_dispatch:

env:
  NODE_VERSION: "22"

jobs:
  test:
    name: Test - Core Microservice
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./apps/core_microservice

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
